name: CI

on:
  push:
    paths:
      - code/**
    branches:
      - main
  workflow_dispatch:

jobs:
  ci:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]
        python-version: [ "3.12" ]
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install dependencies
        working-directory: code
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.dev.txt

      - name: Check types
        working-directory: code
        run: |
          mypy --config pyproject.toml .

      - name: Lint codebase
        working-directory: code
        run: |
          ruff .

      - name: Run tests
        working-directory: code
        run: |
          pytest
